[env:m5stack-core]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -DCORE_DEBUG_LEVEL=0
lib_deps =
    m5stack/M5Unified@^0.2.7
    bblanchon/ArduinoJson@^7
; If PlatformIO cannot auto-pick the port, uncomment and set explicitly:
; upload_port = /dev/cu.usbserial-56750019571
; monitor_port = /dev/cu.usbserial-56750019571
